---
# Install the latest Python 3 version
- name: install python and aws dependencies on ansible host
  hosts: localhost
  roles:
     - role: staticdev.pyenv
       pyenv_path: "/tmp/pyenv"
       pyenv_owner: "root"
       pyenv_global:
         - 3.6.4
       pyenv_enable_autocompletion: false
       pyenv_python_versions:
         - 3.6.4

  tasks:
  - name: see versions
    shell:
      cmd: |
        export PATH="/tmp/pyenv/shims:$PATH"
        . /tmp/pyenv/.pyenvrc && eval "$(pyenv init --path)"
        . /tmp/pyenv/.pyenvrc && pyenv versions
        . /tmp/pyenv/.pyenvrc && pyenv global 3.6.4
  - name: check python version
    shell:
      cmd: |
        python -V
