---
# Install the latest Python 3 version
- name: install python and aws dependencies on ansible host
  hosts: localhost
  roles:
    - role: pyenvRole
  tasks:
  - name: install python
    shell: pyenv install 3.6.4
  - name: check available versions
    shell: pyenv versions
