---
# Install the latest Python 3 version
- name: install python and aws dependencies on ansible host
  hosts: localhost
  roles:
     - role: staticdev.pyenv
       pyenv_path: "/tmp/pyenv"
       pyenv_owner: "root"
       pyenv_global:
         - 3.6.4
       pyenv_enable_autocompletion: false
       pyenv_python_versions:
         - 3.6.4

  tasks:
  - name: check available versions
    shell: which /tmp/pyenv/pyenv/.pyenv
  - name: install python
    shell: /tmp/pyenv/pyenv/.pyenv install 3.6.4
