---
# Install the latest Python 3 version
- name: install python and aws dependencies on ansible host
  hosts: localhost
  roles:
     - role: staticdev.pyenv
       pyenv_path: "/tmp/pyenv"
       pyenv_owner: "root"
       pyenv_global:
         - 3.6.4
       pyenv_enable_autocompletion: false
       pyenv_python_versions:
         - 3.6.4

  tasks:
  - name: see pyenv install files
    shell:
      cmd: |
        search_dir=/tmp/pyenv/
        for entry in "$search_dir"/*
        do
          echo "$entry"
        done
  - name: see all
    shell:
      cmd: |
        ls -a /tmp/pyenv/
  - name: add pyenv to path
    shell:
      cmd: |
        export PATH="/tmp/pyenv/bin:$PATH"
  - name: see versions
    shell:
      cmd: |
        . {{ pyenv_path }}/.pyenvrc && pyenv versions
