---
# Install the latest Python 3 version
- name: install python and aws dependencies on ansible host
  hosts: localhost
  collections:
    - amazon.aws
  roles:
     - role: staticdev.pyenv
       pyenv_path: "/tmp/pyenv"
       pyenv_owner: "root"
       pyenv_global:
         - 3.6.4
       pyenv_enable_autocompletion: false
       pyenv_python_versions:
         - 3.6.4
  tasks:
  - name: see versions
    shell:
      cmd: |
        export PATH="/tmp/pyenv/shims:$PATH"
        eval "$(. /tmp/pyenv/.pyenvrc && pyenv init --path)"
        . /tmp/pyenv/.pyenvrc && pyenv versions
        . /tmp/pyenv/.pyenvrc && pyenv global 3.6.4
        unset PYTHONPATH
        pip install --user boto3 botocore

  - amazon.aws.ec2_instance:
      name: "test-instance"
      key_name: "ansiblePair"
      vpc_subnet_id: subnet-0d554bcace17db73d
      instance_type: t2.medium
      security_group: default
      network:
        assign_public_ip: true
      image_id: ami-0b9ecb12083282d75
      tags:
        Environment: Testing
